### ISSUE TITLE
compileSdkVersion 27点击商品后的上滑进入详情下滑退出等逻辑报错

### ISSUE THREAD

**Issue by yiming8988** [wudifamo/Neleme#9]
compileSdkVersion 27
implementation 'com.android.support:appcompat-v7:27.1.1'
implementation 'com.android.support:design:27.1.1'点击商品后的上滑进入详情下滑退出等逻辑报错

**Comment by wudifamo** [comment]
错误日志都不贴的吗?
做的时候用的是26
27可能是coordinatorlayout的重载方法变了,onNestedPreScroll之类的,自己调下吧

**Comment by yiming8988** [comment]
不好意思   错误日志：
       java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.design.widget.AppBarLayout.getWidth()' on a null object reference
                      at com.k.neleme.detail.DetailHeaderBehavior.judgeDrag(DetailHeaderBehavior.java:161)
                      at com.k.neleme.detail.DetailHeaderBehavior.onTouchEvent(DetailHeaderBehavior.java:135)
                      at com.k.neleme.detail.DetailHeaderBehavior.onTouchEvent(DetailHeaderBehavior.java:22)

onLayoutChild方法并没有被调用
